stages:
  - build
  - test
  - deploy

image: maven:latest

variables:
  GIT_STRATEGY: clone

build-job:
  stage: build
  tags:
    - dalfcs_docker_kvm
  script:
    - echo "building maven project."
    - mvn clean compile
  only:
    - develop
    - test
    - main

test-job:
  stage: test
  tags:
    - dalfcs_docker_kvm
  script:
    - echo "Execute test case"
    - mvn clean test
  only:
    - develop
    - test
    - main

deploy-test:
  stage: deploy
  tags:
    - dalfcs_docker_kvm
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_TEST_APP_NAME --api-key=$HEROKU_TEST_API_KEY
  only:
    - test

deploy-prod:
  stage: deploy
  tags:
    - dalfcs_docker_kvm
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - main