stages:
  - build

variables:
  GIT_STRATEGY: clone

build-spring-stage:
  stage: build
  tags:
    - grad
  script:
    - $MAVEN_HOME/bin/mvn clean
    - mvn package

#stages:
#  - build
#  - test
#
#variables:
#  GIT_STRATEGY: clone
#
#build:
#  stage: build
#  script:
#    - java -jar target/mywebserviceapp-0.0.1-SNAPSHOT.jar
#  tags:
#    - dalfcs_docker_kvm
#
#test:
#  stage: test
#  script:
#    - ./gradlew -S -g /cache/.gradle -Dorg.gradle.java.home=${JAVA_HOME} clean test
#  tags:
#    - dalfcs_gitlab_docker_ci
#
#
#
#after_script:
#  - echo "End CI"